# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cachy}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Grosser"]
  s.date = %q{2011-06-17}
  s.email = %q{grosser.michael@gmail.com}
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "Rakefile",
    "Readme.md",
    "VERSION",
    "cachy.gemspec",
    "lib/cachy.rb",
    "lib/cachy/memcache_timeout_protection.rb",
    "lib/cachy/memcached_wrapper.rb",
    "lib/cachy/moneta_wrapper.rb",
    "lib/cachy/redis_wrapper.rb",
    "lib/cachy/wrapper.rb",
    "spec/cachy/memcache_timeout_protection_spec.rb",
    "spec/cachy/memcached_wrapper_spec.rb",
    "spec/cachy/moneta_wrapper_spec.rb",
    "spec/cachy/redis_wrapper_spec.rb",
    "spec/cachy_spec.rb",
    "spec/mem_cache.rb",
    "spec/spec_helper.rb",
    "spec/test_cache.rb"
  ]
  s.homepage = %q{http://github.com/grosser/cachy}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Caching library for projects that have many processes or many caches}
  s.test_files = [
    "spec/cachy/memcache_timeout_protection_spec.rb",
    "spec/cachy/memcached_wrapper_spec.rb",
    "spec/cachy/moneta_wrapper_spec.rb",
    "spec/cachy/redis_wrapper_spec.rb",
    "spec/cachy_spec.rb",
    "spec/mem_cache.rb",
    "spec/spec_helper.rb",
    "spec/test_cache.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mini_memory_store>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<mini_memory_store>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<mini_memory_store>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

